{{- if and .Values.hiveServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beecd.fullname" . }}-hive-server
  labels:
    {{- include "beecd.hiveServer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.hiveServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "beecd.hiveServer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "beecd.hiveServer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: hive-server
        image: {{ include "beecd.image" (dict "registry" .Values.image.registry "repository" .Values.hiveServer.image.repository "componentTag" .Values.hiveServer.image.tag "tag" .Values.image.tag "defaultTag" .Chart.AppVersion) }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: grpc
          containerPort: 5180
          protocol: TCP
        env:
        - name: LOG_LEVEL
          value: {{ .Values.hiveServer.env.logLevel | quote }}
        - name: STORAGE_TYPE
          value: {{ .Values.hiveServer.env.storageType | quote }}
        - name: GRPC_TIMEOUT_IN_SECONDS
          value: {{ .Values.hiveServer.env.grpcTimeout | quote }}
        - name: GRPC_KEEP_ALIVE_IN_SECONDS
          value: {{ .Values.hiveServer.env.grpcKeepAlive | quote }}
        envFrom:
        - secretRef:
            name: {{ .Values.hiveServer.database.hive.existingSecret | default (printf "%s-hive-db" (include "beecd.fullname" .)) }}
        - secretRef:
            name: {{ .Values.hiveServer.github.existingSecret | default (printf "%s-github" (include "beecd.fullname" .)) }}
        - secretRef:
            name: {{ .Values.hiveServer.sops.existingSecret | default (printf "%s-sops" (include "beecd.fullname" .)) }}
        - secretRef:
            name: {{ .Values.hiveServer.storage.existingSecret | default (printf "%s-storage" (include "beecd.fullname" .)) }}
        {{- if or .Values.hiveServer.jwt.existingSecret .Values.hiveServer.jwt.secretKey }}
        - secretRef:
            name: {{ .Values.hiveServer.jwt.existingSecret | default (printf "%s-jwt" (include "beecd.fullname" .)) }}
        {{- end }}
        resources:
          {{- toYaml .Values.hiveServer.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: grpc
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "beecd.fullname" . }}-hive-server
  labels:
    {{- include "beecd.hiveServer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hiveServer.service.type }}
  ports:
  - port: {{ .Values.hiveServer.service.port }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    {{- include "beecd.hiveServer.selectorLabels" . | nindent 4 }}
{{- end }}
